apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base

labels:
- pairs:
    app.kubernetes.io/version: staging

patches:
  - target:
      kind: Ingress
    path: ingress.yaml
  - target:
      kind: Deployment
    path: replicas-patch.yaml
  - target:
      kind: Deployment
    path: namespace-patch.yaml
  - target:
      kind: Service
    path: namespace-patch.yaml
  - target:
      kind: Ingress
    path: namespace-patch.yaml
  - target:
      kind: Secret
    path: namespace-patch.yaml
  - target:
      kind: SealedSecret
    path: namespace-patch.yaml
  - target:
      kind: SealedSecret
    path: sealed-secret-patch.yaml
