---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: www-smu
spec:
  encryptedData:
    .dockerconfigjson: AgCbxM5kNAV+UrBP7qUguw+pfxbLR/DNWWga484ZxV2Nu0Xyltf54xz4he5CyqbmQKCckALKQ6HeUaq17VJv6E2BTIqVfEMEPP+jgu++4Mye8Cb/eqabcPYBoggUADbp/bzKOcUrPh9lZQvOGyaRa2n7wT3t4VYD5bd0Dh/yJ+ZIHO87QSdN0EK3gQP9kKxc31pREUziAeNDBrgcq98wM4EdPD0u4gTeT2zlRgtCFszWd0gplxdB8GpJipLpFthdYHnpSfrEe6/wQyd4qJUB+EFbYWre6n3rGqIAAgkAxWBGeMyFP2qlDZBQo2sT01OkcbE1/+2Q6f1GZiicAWayh0e2eTvHWVYHMEJdfc1D04VE97fkA8LhcShGH7kHT+7rPX8oCHt6Ue8hMxCEr/5kV6JRloSIdKvOp3SsU846+F1MajvQtYbRUIiDTPHhdd/bzUds4PNth1y1Np1jqp1YcpjG8uv3d7iRJDjSTzRpN7l5Fs/jjZPiGNUGCRq9THcji1Z414wDHh1k95Bu1AQ+IOhEmbqO503cTooVDRNdUQgyqu93DMwu9nO80tMnSZ4/PlpyngPHHS9PucrAtVb4ZGyEBexmW4wmVkJ1l/lPyZa7xBBrZj8OexpvxslV7jelzInDgF0FBUylkMuz2QtoRCmLgQY7HRy8paSbIHikokrN0b9G0m06R0G2YA9Z9afxeiqaIMG8MQQxvU1HgpR9t2HsI0xkNfiT/7cYqrsfvm4RUrY1FojMxt6FN0sk0gsz5uRg0qkUQ+bSYPFcE3M5AjfCo3Z0LJLfaDYY+j9SPqS2VuFctgBQ92qKt1k8rtAqR7gSiw5dhN5kIu4qH2m6+YbmbA6SGPIQ2uFk/tlOf6nyeiOHalVfb6M=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: www-smu
    type: kubernetes.io/dockerconfigjson
