name: Site Build and Deploy

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t chrissearle/www_smu:${{ github.sha }} .

      - name: Tag staging image
        if: github.ref == 'refs/heads/main'
        run: docker tag chrissearle/www_smu:${{ github.sha }} chrissearle/www_smu:staging

      - name: Tag release image
        if: contains(github.ref, 'tag')
        run: docker tag chrissearle/www_smu:${{ github.sha }} chrissearle/www_smu:latest

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push sha image
        run: docker push chrissearle/www_smu:${{ github.sha }}

      - name: Push staging image
        if: github.ref == 'refs/heads/main'
        run: docker push chrissearle/www_smu:staging

      - name: Push release image
        if: contains(github.ref, 'tag')
        run: docker push chrissearle/www_smu:latest
